name: build_image

# on: push

# concurrency:
#   group: build-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
#   cancel-in-progress: false

env:
  REGION: us

jobs:
  check:
    uses: ./.github/workflows/check.yml
  docker_build:
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - uses: "actions/checkout@v4"
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"
      - name: "setup GCP SDK"
        uses: "google-github-actions/setup-gcloud@v2"
      - name: "use gcloud cli"
        run: "gcloud info"
      - name: "setup docker auth"
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
      - name: docker build
        run: make dockerbuild
      - name: docker push
        run: make dockerpush
