name: check

on: [push, workflow_call]
# on: [workflow_call]

# concurrency:
#   group: check-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
#   cancel-in-progress: false


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install poetry
        run: pip install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: install
        run: poetry install --with=dev
      - name: run checks
        run: make check
      - name: test
        run: make test
